version: 2
jobs:
  build:
    working_directory: /akeneo-app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            pip install \
              docker-compose==1.12.0 \
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/akeneo-app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/akeneo-app.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=akeneo-app -t akeneo-app .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/akeneo-app.tar app
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/akeneo-app.tar
      - deploy:
          name: Push application Docker image
          command: |
              docker login 
              docker tag akeneo-app
              docker push 
            fi
